[package]
name = "white_octopus"
version = "0.1.0"
authors = ["grdvsng <grdvsng@gmail.com>"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
