[package]
name = "white_octopus"
version = "0.1.0"
authors = ["grdvsng <grdvsng@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
chrono = "0.4"
json = "0.12.2"